config/routes.rb
Rails.application.routes.draw do

  namespace :account do
    resources :groups
    resources :posts
  end
  devise_for :users
  root 'groups#index'
  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :title, presence: true
  has_many :posts, dependent: :destroy
  has_many :group_users
  has_many :members, through: :group_users, source: :user

  belongs_to :owner, class_name: "User", foreign_key: :user_id

  def editable_by?(user)
    user && user == owner
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
   before_action :authenticate_user!

   def index
     @groups = current_user.participated_groups
   end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts
  end

  def edit
    #@group = Group.find(params[:id])
    #改成只有user的權限才能修改
    @group = current_user.groups.find(params[:id])
  end

  def create
    #@group = Group.create(group_params)
    #改成只有user的權限才能修改
    @group = current_user.groups.new(group_params)

    if @group.save
      current_user.join!(@group)
      redirect_to groups_path
    else
      render :new
    end

  end

  def update
    #@group = Group.find(params[:id])
    #改成只有user的權限才能修改
    @group = current_user.groups.find(params[:id])

    if @group.update(group_params)
      redirect_to groups_path, notice: "修改討論版成功"
    else
      render :edit
    end
  end

  def destroy
    #@group = Group.find(params[:id])
    #改成只有user的權限才能修改
    @group = current_user.groups.find(params[:id])
    @group.destroy
    redirect_to groups_path, alert: "討論版已刪除"
  end

   def join
   @group = Group.find(params[:id])

   if !current_user.is_member_of?(@group)
     current_user.join!(@group)
     flash[:notice] = "加入本討論版成功！"
   else
     flash[:warning] = "你已經是本討論版成員了！"
   end

   redirect_to group_path(@group)
 end

 def quit
   @group = Group.find(params[:id])

   if current_user.is_member_of?(@group)
     current_user.quit!(@group)
     flash[:alert] = "已退出本討論版！"
   else
     flash[:warning] = "你不是本討論版成員，怎麼退出 XD"
   end

   redirect_to group_path(@group)
 end

  private

  def group_params
    params.require(:group).permit(:title, :description)
  end

end

app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for group do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
<% end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>修改討論版</h1>

  <hr>
  <%= render "form", group: @group %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td>#</td>
          <td><%= link_to(truncate(group.title, length: 15), group_path(group)) %></td>
          <td><%= group.description %></td>
          <td>
            <% if group.editable_by?(current_user) %>
              <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", group_path(group),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>新增討論版</h1>

  <hr>
  <%= render "form", group: @group %>
</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New Post", new_group_post_path(@group), class: "btn btn-warning pull-right") %>
    <% if @group.editable_by?(current_user) %>
      <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right")%>
    <% end %>
       <% if current_user.present? %>
     <% if current_user.is_member_of?(@group) %>
       <%= link_to("Quit Group", quit_group_path(@group), method: :post, class: "btn btn-danger") %>
     <% else %>
       <%= link_to("Join Group", join_group_path(@group), method: :post, class: "btn btn-info") %>
     <% end %>
   <% end %>
  </div>
  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>

 <table class="table">
   <thead>
     <tr>
       <th>文章</th>
       <th colspan="2"></th>
     </tr>
   </thead>
   <tbody>
     <% @posts.each do |post| %>
       <tr>
         <td><%= simple_format(post.content) %></td>
         <td>
           <% if post.editable_by?(current_user) %>
             <%= link_to("Edit", edit_group_post_path(post.group, post),
                         class: "btn btn-default btn-xs")%>
             <%= link_to("Delete", group_post_path(post.group, post),
                         class: "btn btn-default btn-xs ", method: :delete,
                         data: { confirm: "Are you sure?" } )%>
           <% end %>
         </td>
       </tr>
     <% end %>
   </tbody>
 </table>
</div>